spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_test_db_name
    username: your_test_db_username
    password: your_test_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # or 'create-drop' for a fresh schema in each test run
